server:
  port: 8877
spring:
  shardingsphere:
    datasource:
      names: m1  # ??????? ????? m1,m2,m3
      m1: # ?????
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_order?serverTimezone=UTC
        username: root
        password: root
    sharding:
      tables: # ????
        user_course_order: # ????
          actualDataNodes: m1.user_course_order_$->{0..4} #????????
          keyGenerator: # ?????
            column: id   # ???
            type: SNOWFLAKE # ??????????long
          tableStrategy: # ??????  ?id?5????? xx_0 xx_1 xx_2..?
            inline:
              shardingColumn: id
              algorithmExpression: user_course_order_$->{id%5}
    props:
      sql:
        show: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guolong
    password: 123456
    virtual-host: myhost
  redis:
    host: 192.168.86.88
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: 100ms
        max-idle: 100
        min-idle: 10
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel ??????
        port: 8719  # sentinel???
    nacos:
      discovery:
        server-addr: 192.168.86.88:8848

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/edu_order?serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
#    username: root
#    password: root
  main:
    allow-bean-definition-overriding: true

weixin:
  pay:
    appId: wx307113892f15a42e
    partner: 1508236581
    partnerKey: HJd7sHGHd6djgdgFG5778GFfhghghgfg
    notifyUrl: http://9gxnin.natappfree.cc





mybatis-plus:
  type-aliases-package: com.gl.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


