server:
  port: 8001
spring:
  redis:
    host: 192.168.86.88
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: 100ms
        max-idle: 100
        min-idle: 10

  application:
    name: ad-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel ??????
        port: 8719  # sentinel???
    nacos:
      discovery:
        server-addr: 192.168.86.88:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu_ad?serverTimezone=UTC
    username: root
    password: root



mybatis:
  type-aliases-package: com.gl.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  type-aliases-package: com.gl.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




